[workspace]

resolver = "2"

members = [
    "cli/core",
    "cli/modules/common",
    "cli/modules/inspect",
    "cli/modules/forward",
    "cli/modules/pipeline",
    "cli/modules/nat64",
    "modules/decap/cli",
    "modules/route/cli/neighbour",
    "modules/route/cli/route",
    "web",
]

[profile.release]
panic = "abort"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
debug = true
