# Coordinator configuration.
coordinator:
  # Coordinator gRPC endpoint for external module registration.
  endpoint: "[::1]:50052"

# Gateway configuration.
gateway:
  # Gateway API endpoint.
  endpoint: "[::1]:8080"

# Multi-stage configuration.
stages:
  # Stage 1: Bootstrap.
  - name: bootstrap
    # Per-instance configuration within this stage
    instance:
      # Instance 0
      0:
        modules:
          forward:
            config_name: "forward-bootstrap0"
            config_path: "modules/forward/etc/yanet/forward-bootstrap.yaml"
          route:
            config_name: "route-bootstrap0"
            config_path: "modules/route/etc/yanet/route-bootstrap.yaml"
        pipelines:
          - name: bootstrap
            chain:
              - module_name: "forward"
                config_name: "forward-bootstrap0"
              - module_name: "route"
                config_name: "route-bootstrap0"
          - name: decap
            chain:
              - module_name: "forward"
                config_name: "forward-bootstrap0"
              - module_name: "route"
                config_name: "route-bootstrap0"
        devices:
          - id: 0
            pipelines:
              - name: decap
                weight: 1
          - id: 1
            pipelines:
              - name: bootstrap
                weight: 1
