[package]
name = "yanet-cli-decap"
version = "0.1.0"
edition = "2024"
publish = false

rust-version = "1.85"

[dependencies]
ync = { path = "../../../cli/core", version = "0.1", package = "yanet-cli" }
bitmap = { path = "../../../common/rust/bitmap", version = "0.1" }
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
tokio = { version = "1", features = ["rt", "net", "time", "macros", "sync"] }
prost = "0.13"
prost-types = "0.13"
tonic = { version = "0.13" }
ipnet = "2"
colored = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ptree = "0.5"

[build-dependencies]
tonic-build = "0.13"
