[workspace]

resolver = "2"

members = [
    "core",
    "modules/common",
    "modules/inspect",
    "modules/decap",
    "modules/route",
    "modules/neighbour",
    "modules/forward",
    "modules/pipeline",
    "modules/nat64",
]

[profile.release]
panic = "abort"
