[package]
name = "yanet-cli"
version = "0.1.0"
edition = "2021"
publish = false

rust-version = "1.84"

[dependencies]
log = "0.4"
simple_logger = { version = "5", features = ["timestamps"] }
colored = "3"
