name: Build YANET

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: yanetplatform/yanet2-base:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: hendrikmuhs/ccache-action@v1.2.11
        name: ccache
        with:
          key: ${{ runner.os }}-build-cache
      - run: |
          meson setup build -Dbuildtype=debug
          meson compile -C build
