name: Build YANET

on:
  push:
    branches: ["main"]
    paths: ["**.h", "**.c", "**/meson.build"]
  pull_request:
    branches: ["main"]
    paths: ["**.h", "**.c", "**/meson.build"]

jobs:
  build:
    runs-on: ubuntu-24.04    
    steps:      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: meson clang python3-pyelftools libnuma-dev libpcap-dev git
          version: 1.0
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: hendrikmuhs/ccache-action@v1.2.11
        name: ccache
        with:
          key: ${{ runner.os }}-build-cache
      - run: |
          meson setup build -Dbuildtype=debug
          meson compile -C build
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: build
          style: file
          # Use .clang-tidy config file.
          tidy-checks: ''
          version: 19
          thread-comments: false
          step-summary: true
          tidy-review: false
          format-review: false
          files-changed-only: true
          ignore: '.github|build'
      - name: Check code style violation
        if: steps.linter.outputs.clang-tidy-checks-failed > 0
        run: exit 1
