name: Formatting check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: 19
          exclude-regex: subprojects/.*
