name: Go Formatting Check

on:
  push:
    branches: [ main, master ]
    paths:
      - 'controlplane/**/*.go'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'controlplane/**/*.go'

jobs:
  gofmt:
    name: Check Go Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: true
          cache-dependency-path: controlplane/go.sum

      - name: Check gofmt
        run: |
          cd controlplane
          # Find Go files that are not properly formatted
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted properly:"
            echo "$unformatted"
            exit 1
          fi
